name: CI for Playwright/Cypress

on:
  push:
    paths:
      - 'playwright/**'
      - 'cypress/**'
  pull_request:
    paths:
      - 'playwright/**'
      - 'cypress/**'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
      playwright_changed: ${{ steps.set.outputs.playwright }}
      cypress_changed: ${{ steps.set.outputs.cypress }}
    steps:
      - uses: actions/checkout@v4
      - id: set
        run: |
          PLAYWRIGHT=false
          CYPRESS=false
          FOLDERS=()

          DST=${{ github.event.before }}
          SRC=${{ github.sha }}

          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            DST=${{ github.event.pull_request.base.sha }}
            #SRC=${{ github.event.pull_request.head.sha }}
          fi

          echo "Event: ${{ github.event_name }}"
          echo "DST: $DST"
          echo "SRC: $SRC"

          git fetch origin $DST --depth=1
          changed=$(git diff --name-only $DST $SRC)

          if echo "$changed" | grep -q '^playwright/'; then
            FOLDERS+=("playwright")
            PLAYWRIGHT=true
          fi

          if echo "$changed" | grep -q '^cypress/'; then
            FOLDERS+=("cypress")
            CYPRESS=true
          fi

          MATRIX_JSON=$(printf '%s\n' "${FOLDERS[@]}" | jq -R . | jq -s .)
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "matrix<<$EOF" >> $GITHUB_OUTPUT
          echo "$MATRIX_JSON" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
          echo "playwright=$PLAYWRIGHT" >> $GITHUB_OUTPUT
          echo "cypress=$CYPRESS" >> $GITHUB_OUTPUT

  lint:
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ${{ fromJson(needs.detect-changes.outputs.matrix) }}
    name: Lint ${{ matrix.folder }}
    container:
      image: node:22-slim
    steps:
      - uses: actions/checkout@v4
      - name: check node
        run: node -v
      - name: Install dependecies
        working-directory: ./${{ matrix.folder }}
        run: |
          echo "PWD: $(pwd)"
          echo "Matrix folder: ${{matrix.folder}}"
          npm i
      - name: Run lint
        working-directory: ./${{ matrix.folder }}
        run: npm run lint


  test-playwright:
    name: Run playwright tests
    needs: [lint, detect-changes]
    if: needs.detect-changes.outputs.playwright_changed == 'true'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.52.0
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: ./playwright
        run: npm ci
      - name: Run e2e tests
        working-directory: ./playwright
        run: npm run test:chromium:all
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-default
          path: |
                playwright/playwright-report/
                playwright/test-results/
          retention-days: 10

  tests-cypress-chrome: 
    name: 'Run cypress tests in chrome'
    needs: [lint, detect-changes]
    if: needs.detect-changes.outputs.cypress_changed == 'true'
    runs-on: ubuntu-latest
    container:
     image: cypress/included:latest
     options: --user 1001
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: cypress
        run: npm ci
      - uses: cypress-io/github-action@v6
        with:
          browser: chrome
          working-directory: cypress

  tests-cypress-firefox: 
    name: 'Run cypress tests in firefox'
    needs: [lint, detect-changes, tests-cypress-chrome]
    if: needs.detect-changes.outputs.cypress_changed == 'true'
    runs-on: ubuntu-latest
    container:
     image: cypress/included:latest
     options: --user 1001
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: cypress
        run: npm ci
      - uses: cypress-io/github-action@v6
        with:
          browser: firefox
          working-directory: cypress