name: Sync Workflow Changes

on:
  push:
    paths:
      - '.github/workflows/**'

jobs:
  sync-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get current branch name
        id: vars
        run: echo "branch=$(git rev-parse --abbrev-ref HEAD)" >> "$GITHUB_OUTPUT"

      - name: Get all remote branches
        run: |
          git fetch origin
          git branch -r | grep -v "\->" | sed 's|origin/||' | grep -v "^${{ steps.vars.outputs.branch }}$" > branches.txt

      - name: Sync workflows to other branches
        run: |
          for branch in $(cat branches.txt); do
            git checkout $branch
            git checkout ${{ steps.vars.outputs.branch }} -- .github/workflows
            git add .github/workflows
            git commit -m "Sync workflows from ${{ steps.vars.outputs.branch }}" || echo "No changes to commit"
            git push origin $branch
          done
